### ISSUE TITLE
Harden interrupted availability

### ISSUE THREAD

**Issue by robertkowalski** [bitfinexcom/grenache-nodejs-base#1]
Given the server, e.g. a RPC worker, is down or not started and a procedure is sended from a client, it will error with `ERR_GRAPE_LOOKUP_EMPTY` and then hangs around as a zombie (given we all other workers just died/are unavailable as well).

As a developer I would expect that it tries until the server is back up again, e.g. with a retry algorithm that doesn't hammer the network.

**Comment by prdn** [comment]
@robertkowalski my initial thought was to offer a bare implementation and leave the retry to the dev :-)
Did not want to over complicate things but we might add it as an option indeed

**Comment by robertkowalski** [comment]
ah, good idea!

**Comment by tchapu** [comment]
I have this message too when I try to connect to Tokinex : ERR_GRAPE_LOOKUP_EMPTY

**Comment by soring323** [comment]
server is live but getting this issue. 
I'm using Mac, I've turn off my firewall. but getting same issue.

Many things for any kind of help. 
Thank you
