### ISSUE TITLE
release 0.2.0

### ISSUE THREAD

**Issue by robertkowalski** [bitfinexcom/grenache-nodejs-base#4]
I think a new release is due, this will also fix the red travis builds from the peers which depends on base.

can you run this for me in the base directory, to publish a new version?

```
npm version minor
npm publish
git push origin master --tags
```

Explanation:
npm version will create a commit & git tag with the version number 0.2.0 (useful for diffing between versions, but you can also use it to check out code via git)

`--tags` pushes them to github and they appear in the tag section of the "branches-dropdown" and on the release pages.

**Comment by prdn** [comment]
@robertkowalski done

**Comment by robertkowalski** [comment]
thx :)
